version: '3.7'
services:
    tensorflow:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tensorflow
        volumes:
            - ./dqncatp:/home/
        tty: true
        command: /bin/bash
        ports:
            - 8889:8889
