version: '3.7'
services:
    tensorflow:
        container_name: tensorflow
        image: tensorflow/tensorflow:latest-py3-jupyter
        volumes:
            - ./dqncatp:/home/
        tty: true
        command: /bin/bash
        ports:
            - 8889:8889
