version: '3.7'
services:
    tensorflow:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: tensorflow
        volumes:
            - ./dqncatp:/catp/dqncatp/
            - ./catpvalidator:/catp/catpvalidator/
            - ./catptools:/catp/catptools/
            - ./catpframework:/catp/catpframework/
        tty: true
        command: /bin/bash
        ports:
            - 8889:8889
